#!/bin/sh
python3 /usr/local/lib/antman_tester/generator.py $1
FILE=antman/antman
if [ -f $FILE ]
then
    ./antman test 1 > compressed_file
    python3 /usr/local/lib/antman_tester/pourcentage.py test compressed_file
    FILE2=giantman/giantman
    if [ -f $FILE2 ]
    then
        ./giantman compressed_file 1 > final_file
        echo "file" > f1
        echo "file" > f2
        good=$(bash -c "diff f1 f2")
        diff=$(bash -c "diff final_file test")
        OUTPUT=$(< test)
        OUTPUT2=$(< final_file)
        if [[ $diff == $good ]]
        then
            tput setaf 2
            echo "Antman 0K"
            tput init
        else
            tput setaf 1
            echo "Antman K0 : Output different from expected output"
            tput init
            echo "Expected :"
            echo "$OUTPUT"
            echo "But Got :"
            echo "$OUTPUT2"
        fi
        rm -f f1
        rm -f f2
        rm -f final_file
    else
        tput setaf 1
        echo "[ERROR] : giantman file not found"
        tput setaf init
    fi
    rm -f compressed_file
else
    tput setaf 1
    echo "[ERROR] : antman file not found"
    tput setaf init
fi
rm -rf test
